2020-04-25 06:53:04,107:INFO:------------------------------------------------------------------------------------------------
2020-04-25 07:01:44,709:INFO:------------------------------------------------------------------------------------------------
2020-04-25 07:10:39,843:INFO:------------------------------------------------------------------------------------------------
2020-04-25 07:53:04,408:INFO:------------------------------------------------------------------------------------------------
2020-04-25 08:01:49,449:INFO:------------------------------------------------------------------------------------------------
2020-04-25 08:10:42,156:INFO:------------------------------------------------------------------------------------------------
2020-04-25 08:53:04,750:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:01:54,153:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:10:44,512:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:13:31,030:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:18:39,032:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:18:39,033:INFO:2
2020-04-25 09:18:49,327:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:18:52,087:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:18:52,088:INFO:2
2020-04-25 09:18:52,362:WARNING:Not Found: /favicon.ico
2020-04-25 09:18:55,681:WARNING:Not Found: /favicon.ico
2020-04-25 09:19:40,443:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:19:40,444:INFO:2
2020-04-25 09:19:53,653:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:19:53,653:INFO:2
2020-04-25 09:20:06,732:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:20:06,733:INFO:2
2020-04-25 09:20:31,301:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:20:33,558:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:20:33,558:INFO:4
2020-04-25 09:21:07,210:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:21:07,210:INFO:4
2020-04-25 09:21:08,229:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:21:08,230:INFO:4
2020-04-25 09:21:09,265:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:21:09,266:INFO:4
2020-04-25 09:21:20,484:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:21:20,484:INFO:4
2020-04-25 09:21:26,647:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:21:26,647:INFO:4
2020-04-25 09:21:40,497:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:21:40,497:INFO:4
2020-04-25 09:21:59,502:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:22:01,966:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:22:01,966:INFO:7
2020-04-25 09:22:05,165:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:22:05,165:INFO:7
2020-04-25 09:22:22,603:INFO:ДУГААРЫН ҮНЭ
2020-04-25 09:22:22,606:INFO:10000
2020-04-25 09:22:29,511:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:22:29,511:INFO:7
2020-04-25 09:22:40,314:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:22:40,315:INFO:7
2020-04-25 09:22:41,212:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:22:46,142:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:22:46,142:INFO:7
2020-04-25 09:22:48,896:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:22:48,896:INFO:7
2020-04-25 09:22:49,737:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:22:49,737:INFO:7
2020-04-25 09:22:56,554:INFO:ДУГААРЫН ҮНЭ
2020-04-25 09:22:56,557:INFO:10000
2020-04-25 09:23:08,184:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:23:08,184:INFO:7
2020-04-25 09:23:23,598:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:23:23,598:INFO:7
2020-04-25 09:23:25,818:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:23:33,128:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:23:33,128:INFO:4
2020-04-25 09:24:17,079:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:24:20,190:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:24:20,190:INFO:7
2020-04-25 09:24:47,186:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:24:47,186:INFO:7
2020-04-25 09:24:47,625:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:24:47,625:INFO:7
2020-04-25 09:24:48,156:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:24:48,839:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:24:48,839:INFO:7
2020-04-25 09:28:12,936:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:28:12,936:INFO:7
2020-04-25 09:28:24,221:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:28:24,222:INFO:7
2020-04-25 09:28:28,580:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:28:33,426:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:28:33,427:INFO:7
2020-04-25 09:28:51,070:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:28:55,560:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:28:55,560:INFO:4
2020-04-25 09:28:56,910:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:28:58,199:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:28:58,199:INFO:2
2020-04-25 09:29:00,405:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:29:00,406:INFO:2
2020-04-25 09:29:33,955:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:29:38,707:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:29:38,707:INFO:7
2020-04-25 09:32:47,132:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:32:47,132:INFO:7
2020-04-25 09:32:48,096:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:32:54,390:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:32:54,390:INFO:7
2020-04-25 09:33:00,811:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:33:05,373:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:33:05,373:INFO:7
2020-04-25 09:33:23,675:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:33:24,800:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:33:24,800:INFO:7
2020-04-25 09:33:30,835:INFO:ДУГААРЫН ҮНЭ
2020-04-25 09:33:30,838:INFO:10000
2020-04-25 09:34:39,533:INFO:ДУГААРЫН ҮНЭ
2020-04-25 09:34:39,535:INFO:10000
2020-04-25 09:35:15,737:INFO:ДУГААРЫН ҮНЭ
2020-04-25 09:35:15,740:INFO:10000
2020-04-25 09:36:32,578:INFO:ДУГААРЫН ҮНЭ
2020-04-25 09:36:32,581:INFO:10000
2020-04-25 09:37:34,258:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:37:36,590:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:37:36,590:INFO:2
2020-04-25 09:37:36,870:WARNING:Not Found: /favicon.ico
2020-04-25 09:37:38,325:INFO:ДУГААРЫН ZAHIALGA
2020-04-25 09:37:39,952:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:37:39,952:INFO:7
2020-04-25 09:37:40,692:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:37:42,781:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:37:42,781:INFO:7
2020-04-25 09:37:57,892:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:37:59,152:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:37:59,152:INFO:7
2020-04-25 09:40:07,603:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:40:07,603:INFO:7
2020-04-25 09:40:39,809:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:40:41,386:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:40:41,386:INFO:2
2020-04-25 09:40:43,334:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:40:43,334:INFO:2
2020-04-25 09:40:48,633:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:40:48,634:INFO:2
2020-04-25 09:40:58,577:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:40:58,578:INFO:2
2020-04-25 09:40:59,356:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:40:59,356:INFO:2
2020-04-25 09:40:59,746:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:41:00,508:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:41:00,508:INFO:7
2020-04-25 09:41:01,851:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:41:01,851:INFO:7
2020-04-25 09:41:25,033:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:41:25,033:INFO:2
2020-04-25 09:41:26,098:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:41:26,098:INFO:7
2020-04-25 09:41:26,987:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:41:27,985:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:41:27,985:INFO:4
2020-04-25 09:41:29,312:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:41:29,312:INFO:4
2020-04-25 09:41:52,579:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:41:52,579:INFO:4
2020-04-25 09:41:53,524:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:41:55,975:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:41:55,975:INFO:7
2020-04-25 09:41:59,881:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:42:18,791:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:42:19,706:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:42:19,706:INFO:7
2020-04-25 09:42:21,826:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:42:21,826:INFO:7
2020-04-25 09:42:35,496:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:42:36,444:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:42:36,444:INFO:7
2020-04-25 09:42:39,456:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:42:39,456:INFO:7
2020-04-25 09:42:49,973:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:42:49,974:INFO:7
2020-04-25 09:42:54,677:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:42:55,377:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:42:55,377:INFO:2
2020-04-25 09:42:56,916:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:42:56,916:INFO:7
2020-04-25 09:42:59,335:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:42:59,336:INFO:2
2020-04-25 09:43:40,493:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:43:40,494:INFO:2
2020-04-25 09:43:51,715:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:43:51,716:INFO:2
2020-04-25 09:43:53,062:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:43:53,836:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:43:53,836:INFO:7
2020-04-25 09:43:56,310:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:43:56,310:INFO:7
2020-04-25 09:44:14,206:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:44:17,453:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:44:17,454:INFO:7
2020-04-25 09:45:02,887:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:45:02,887:INFO:7
2020-04-25 09:45:03,984:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:45:03,984:INFO:7
2020-04-25 09:45:32,883:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:45:34,177:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:45:34,177:INFO:2
2020-04-25 09:45:42,630:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:45:42,630:INFO:2
2020-04-25 09:46:01,342:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:46:01,342:INFO:2
2020-04-25 09:46:04,696:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:46:05,385:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:46:05,385:INFO:4
2020-04-25 09:46:07,495:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:46:07,495:INFO:4
2020-04-25 09:46:22,729:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:46:25,316:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:46:25,317:INFO:4
2020-04-25 09:46:56,152:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:46:58,012:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:46:58,013:INFO:4
2020-04-25 09:47:00,969:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:47:01,548:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:47:01,548:INFO:4
2020-04-25 09:47:04,727:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:47:04,727:INFO:4
2020-04-25 09:47:40,733:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:47:44,729:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:47:44,730:INFO:7
2020-04-25 09:47:48,925:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:47:48,926:INFO:7
2020-04-25 09:47:54,490:INFO:ДУГААРЫН ҮНЭ
2020-04-25 09:47:54,494:INFO:10000
2020-04-25 09:48:36,522:INFO:ДУГААРЫН ZAHIALGA
2020-04-25 09:48:38,925:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:48:41,096:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:48:41,096:INFO:7
2020-04-25 09:48:42,504:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:48:42,504:INFO:7
2020-04-25 09:48:49,331:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:48:49,331:INFO:7
2020-04-25 09:48:49,939:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:53:05,062:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:57:29,453:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:57:29,454:INFO:2
2020-04-25 09:57:32,611:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:57:38,701:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:57:38,702:INFO:4
2020-04-25 09:57:39,085:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:57:39,085:INFO:7
2020-04-25 09:57:39,474:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:57:39,749:INFO:------------------------------------------------------------------------------------------------
2020-04-25 09:57:40,143:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:57:40,143:INFO:7
2020-04-25 09:57:40,457:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 09:57:40,458:INFO:4
2020-04-25 09:59:57,093:INFO:------------------------------------------------------------------------------------------------
2020-04-25 10:00:10,648:INFO:------------------------------------------------------------------------------------------------
2020-04-25 10:01:58,860:INFO:------------------------------------------------------------------------------------------------
2020-04-25 10:03:36,071:INFO:------------------------------------------------------------------------------------------------
2020-04-25 10:05:47,093:INFO:------------------------------------------------------------------------------------------------
2020-04-25 10:08:22,329:INFO:------------------------------------------------------------------------------------------------
2020-04-25 10:08:28,334:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 10:08:28,334:INFO:2
2020-04-25 10:08:28,503:WARNING:Not Found: /favicon.ico
2020-04-25 10:10:46,817:INFO:------------------------------------------------------------------------------------------------
2020-04-25 10:12:17,725:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 10:12:17,725:INFO:7
2020-04-25 10:12:24,641:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 10:12:24,642:INFO:7
2020-04-25 10:12:28,636:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 10:12:28,637:INFO:7
2020-04-25 10:14:57,074:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 10:14:57,075:INFO:7
2020-04-25 10:16:00,747:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 10:16:00,747:INFO:7
2020-04-25 10:16:09,878:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 10:16:09,879:INFO:7
2020-04-25 10:16:22,390:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 10:16:22,391:INFO:7
2020-04-25 10:16:24,801:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 10:16:24,801:INFO:7
2020-04-25 10:17:42,315:INFO:------------------------------------------------------------------------------------------------
2020-04-25 10:27:10,256:INFO:------------------------------------------------------------------------------------------------
2020-04-25 10:29:20,195:INFO:ДУГААРЫН ҮНЭ
2020-04-25 10:29:20,199:INFO:10000
2020-04-25 10:29:28,635:INFO:ДУГААРЫН ҮНЭ
2020-04-25 10:29:28,637:INFO:10000
2020-04-25 10:30:55,384:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 10:30:55,384:INFO:2
2020-04-25 10:32:15,366:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 10:32:15,366:INFO:2
2020-04-25 10:32:34,542:INFO:ДУГААРЫН ҮНЭ
2020-04-25 10:32:34,544:INFO:5000
2020-04-25 10:34:50,859:INFO:ДУГААРЫН ҮНЭ
2020-04-25 10:34:50,862:INFO:10000
2020-04-25 10:42:02,397:INFO:------------------------------------------------------------------------------------------------
2020-04-25 10:46:23,753:INFO:------------------------------------------------------------------------------------------------
2020-04-25 10:46:25,613:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 10:46:25,613:INFO:7
2020-04-25 10:46:25,969:WARNING:Not Found: /favicon.ico
2020-04-25 10:47:34,067:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 10:47:34,067:INFO:7
2020-04-25 10:47:43,059:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 10:47:45,102:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 10:47:45,333:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 10:47:45,526:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 10:47:47,957:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 10:52:14,538:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 10:52:14,538:INFO:2
2020-04-25 10:52:15,151:WARNING:Not Found: /favicon.ico
2020-04-25 10:53:05,461:INFO:------------------------------------------------------------------------------------------------
2020-04-25 10:53:13,042:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 10:53:13,042:INFO:2
2020-04-25 10:57:39,591:INFO:------------------------------------------------------------------------------------------------
2020-04-25 10:57:39,864:INFO:------------------------------------------------------------------------------------------------
2020-04-25 10:59:45,704:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 10:59:45,704:INFO:4
2020-04-25 10:59:46,474:WARNING:Not Found: /favicon.ico
2020-04-25 10:59:46,514:WARNING:Not Found: /favicon.ico
2020-04-25 10:59:47,852:INFO:------------------------------------------------------------------------------------------------
2020-04-25 10:59:48,744:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 10:59:48,744:INFO:2
2020-04-25 11:00:14,674:INFO:------------------------------------------------------------------------------------------------
2020-04-25 11:00:24,770:INFO:------------------------------------------------------------------------------------------------
2020-04-25 11:01:15,629:INFO:------------------------------------------------------------------------------------------------
2020-04-25 11:01:24,271:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:01:24,271:INFO:7
2020-04-25 11:01:25,053:WARNING:Not Found: /favicon.ico
2020-04-25 11:01:27,782:INFO:------------------------------------------------------------------------------------------------
2020-04-25 11:01:28,517:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:01:28,517:INFO:2
2020-04-25 11:01:32,833:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:01:32,833:INFO:2
2020-04-25 11:02:00,472:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:02:00,472:INFO:2
2020-04-25 11:02:03,861:INFO:------------------------------------------------------------------------------------------------
2020-04-25 11:02:30,594:INFO:ДУГААРЫН ҮНЭ
2020-04-25 11:02:30,597:INFO:5000
2020-04-25 11:02:38,738:INFO:ДУГААРЫН ZAHIALGA
2020-04-25 11:02:42,074:INFO:------------------------------------------------------------------------------------------------
2020-04-25 11:02:43,056:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:02:43,057:INFO:2
2020-04-25 11:02:52,843:INFO:ДУГААРЫН ҮНЭ
2020-04-25 11:02:52,845:INFO:5000
2020-04-25 11:02:55,367:INFO:ДУГААРЫН ZAHIALGA
2020-04-25 11:02:56,261:INFO:------------------------------------------------------------------------------------------------
2020-04-25 11:02:57,066:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:02:57,067:INFO:2
2020-04-25 11:03:10,760:INFO:ДУГААРЫН ҮНЭ
2020-04-25 11:03:10,762:INFO:5000
2020-04-25 11:03:12,834:INFO:ДУГААРЫН ZAHIALGA
2020-04-25 11:03:13,772:INFO:------------------------------------------------------------------------------------------------
2020-04-25 11:03:14,639:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:03:14,639:INFO:2
2020-04-25 11:03:24,173:INFO:ДУГААРЫН ҮНЭ
2020-04-25 11:03:24,175:INFO:5000
2020-04-25 11:03:26,184:INFO:ДУГААРЫН ZAHIALGA
2020-04-25 11:03:27,045:INFO:------------------------------------------------------------------------------------------------
2020-04-25 11:03:28,238:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:03:28,238:INFO:2
2020-04-25 11:05:47,504:INFO:------------------------------------------------------------------------------------------------
2020-04-25 11:06:41,344:INFO:ДУГААРЫН ҮНЭ
2020-04-25 11:06:41,348:INFO:5000
2020-04-25 11:07:28,206:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:07:28,206:INFO:2
2020-04-25 11:08:22,672:INFO:------------------------------------------------------------------------------------------------
2020-04-25 11:10:49,202:INFO:------------------------------------------------------------------------------------------------
2020-04-25 11:12:39,563:INFO:------------------------------------------------------------------------------------------------
2020-04-25 11:12:45,916:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:12:45,917:INFO:7
2020-04-25 11:12:46,247:WARNING:Not Found: /favicon.ico
2020-04-25 11:12:53,018:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 11:12:55,215:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:12:55,215:INFO:7
2020-04-25 11:13:00,585:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:13:00,585:INFO:7
2020-04-25 11:13:11,016:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 11:13:16,100:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 11:13:19,476:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 11:13:22,950:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 11:13:37,259:INFO:------------------------------------------------------------------------------------------------
2020-04-25 11:13:39,532:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:13:39,532:INFO:2
2020-04-25 11:13:39,816:WARNING:Not Found: /favicon.ico
2020-04-25 11:13:39,898:WARNING:Not Found: /favicon.ico
2020-04-25 11:16:14,690:INFO:------------------------------------------------------------------------------------------------
2020-04-25 11:16:24,053:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:16:24,053:INFO:2
2020-04-25 11:17:24,229:INFO:ДУГААРЫН ҮНЭ
2020-04-25 11:17:24,231:INFO:5000
2020-04-25 11:17:43,207:INFO:------------------------------------------------------------------------------------------------
2020-04-25 11:28:16,696:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:28:16,696:INFO:7
2020-04-25 11:28:17,222:WARNING:Not Found: /favicon.ico
2020-04-25 11:28:34,521:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:28:34,522:INFO:7
2020-04-25 11:29:08,337:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:29:08,337:INFO:7
2020-04-25 11:29:08,802:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:29:08,803:INFO:7
2020-04-25 11:30:46,140:INFO:------------------------------------------------------------------------------------------------
2020-04-25 11:30:48,306:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:30:48,307:INFO:3
2020-04-25 11:30:49,687:INFO:------------------------------------------------------------------------------------------------
2020-04-25 11:30:50,619:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:30:50,619:INFO:7
2020-04-25 11:30:53,122:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:30:53,122:INFO:7
2020-04-25 11:31:31,039:INFO:------------------------------------------------------------------------------------------------
2020-04-25 11:34:45,599:INFO:------------------------------------------------------------------------------------------------
2020-04-25 11:34:47,947:INFO:------------------------------------------------------------------------------------------------
2020-04-25 11:34:49,507:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:34:49,507:INFO:7
2020-04-25 11:34:49,783:WARNING:Not Found: /favicon.ico
2020-04-25 11:34:54,977:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:34:54,977:INFO:7
2020-04-25 11:35:10,652:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:35:10,652:INFO:7
2020-04-25 11:35:10,912:WARNING:Not Found: /favicon.ico
2020-04-25 11:35:29,290:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:35:29,291:INFO:7
2020-04-25 11:35:51,819:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:35:51,820:INFO:7
2020-04-25 11:40:11,633:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:40:11,634:INFO:2
2020-04-25 11:40:13,867:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:40:13,867:INFO:2
2020-04-25 11:40:16,587:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:40:16,588:INFO:2
2020-04-25 11:40:18,665:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:40:18,666:INFO:2
2020-04-25 11:40:24,021:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:40:24,021:INFO:2
2020-04-25 11:40:26,366:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:40:26,367:INFO:2
2020-04-25 11:40:27,793:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:40:27,794:INFO:2
2020-04-25 11:40:33,332:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:40:33,332:INFO:2
2020-04-25 11:40:39,588:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:40:39,588:INFO:2
2020-04-25 11:42:02,487:INFO:------------------------------------------------------------------------------------------------
2020-04-25 11:43:46,270:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:43:46,271:INFO:7
2020-04-25 11:44:59,172:INFO:------------------------------------------------------------------------------------------------
2020-04-25 11:45:04,352:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:45:04,353:INFO:7
2020-04-25 11:45:08,476:INFO:------------------------------------------------------------------------------------------------
2020-04-25 11:45:10,324:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:45:10,325:INFO:7
2020-04-25 11:45:10,576:WARNING:Not Found: /favicon.ico
2020-04-25 11:52:23,429:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:52:23,429:INFO:7
2020-04-25 11:52:23,759:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:52:23,759:INFO:7
2020-04-25 11:52:30,747:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:52:30,747:INFO:7
2020-04-25 11:52:43,465:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 11:52:43,465:INFO:7
2020-04-25 11:53:05,896:INFO:------------------------------------------------------------------------------------------------
2020-04-25 11:56:48,531:INFO:ДУГААРЫН ҮНЭ
2020-04-25 11:56:48,533:INFO:10000
2020-04-25 11:56:48,552:INFO:ДУГААРЫН ҮНЭ
2020-04-25 11:56:48,554:INFO:10000
2020-04-25 11:57:39,676:INFO:------------------------------------------------------------------------------------------------
2020-04-25 11:57:39,951:INFO:------------------------------------------------------------------------------------------------
2020-04-25 11:58:54,858:INFO:------------------------------------------------------------------------------------------------
2020-04-25 12:00:17,072:INFO:------------------------------------------------------------------------------------------------
2020-04-25 12:00:26,661:INFO:------------------------------------------------------------------------------------------------
2020-04-25 12:01:46,075:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 12:01:46,075:INFO:7
2020-04-25 12:01:46,999:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 12:01:46,999:INFO:7
2020-04-25 12:02:08,620:INFO:------------------------------------------------------------------------------------------------
2020-04-25 12:05:47,676:INFO:------------------------------------------------------------------------------------------------
2020-04-25 12:08:22,728:INFO:------------------------------------------------------------------------------------------------
2020-04-25 12:10:18,697:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 12:10:18,697:INFO:2
2020-04-25 12:10:24,063:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 12:10:24,063:INFO:2
2020-04-25 12:10:25,212:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 12:10:25,213:INFO:2
2020-04-25 12:10:32,112:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 12:10:32,112:INFO:2
2020-04-25 12:10:50,120:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 12:10:50,120:INFO:2
2020-04-25 12:10:51,579:INFO:------------------------------------------------------------------------------------------------
2020-04-25 12:11:00,992:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 12:11:00,992:INFO:2
2020-04-25 12:11:12,415:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 12:11:12,415:INFO:2
2020-04-25 12:11:34,725:INFO:------------------------------------------------------------------------------------------------
2020-04-25 12:11:42,432:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 12:11:42,433:INFO:2
2020-04-25 12:13:45,436:INFO:ДУГААРЫН ҮНЭ
2020-04-25 12:13:45,438:INFO:5000
2020-04-25 12:13:59,018:INFO:------------------------------------------------------------------------------------------------
2020-04-25 12:17:35,882:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 12:17:35,882:INFO:7
2020-04-25 12:17:43,363:INFO:------------------------------------------------------------------------------------------------
2020-04-25 12:18:17,352:INFO:------------------------------------------------------------------------------------------------
2020-04-25 12:18:19,194:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 12:18:19,195:INFO:2
2020-04-25 12:18:25,242:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 12:18:25,242:INFO:7
2020-04-25 12:18:46,384:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 12:18:46,384:INFO:7
2020-04-25 12:19:12,399:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 12:19:12,399:INFO:7
2020-04-25 12:19:34,162:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 12:19:34,162:INFO:7
2020-04-25 12:23:57,967:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 12:23:57,968:INFO:2
2020-04-25 12:30:35,828:INFO:------------------------------------------------------------------------------------------------
2020-04-25 12:35:40,978:INFO:------------------------------------------------------------------------------------------------
2020-04-25 12:35:53,341:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 12:35:53,341:INFO:7
2020-04-25 12:35:53,586:WARNING:Not Found: /favicon.ico
2020-04-25 12:39:50,747:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 12:39:50,747:INFO:7
2020-04-25 12:40:01,091:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 12:40:01,091:INFO:3
2020-04-25 12:40:09,938:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 12:40:09,938:INFO:3
2020-04-25 12:40:15,442:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 12:40:15,442:INFO:3
2020-04-25 12:40:50,161:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 12:40:50,161:INFO:3
2020-04-25 12:43:24,307:INFO:------------------------------------------------------------------------------------------------
2020-04-25 12:43:25,394:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 12:43:25,395:INFO:2
2020-04-25 12:43:56,238:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 12:43:56,239:INFO:2
2020-04-25 12:44:03,934:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 12:44:03,935:INFO:2
2020-04-25 12:46:09,389:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 12:46:09,390:INFO:2
2020-04-25 12:46:14,012:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 12:46:14,012:INFO:2
2020-04-25 12:47:40,894:INFO:------------------------------------------------------------------------------------------------
2020-04-25 12:53:06,309:INFO:------------------------------------------------------------------------------------------------
2020-04-25 12:57:39,782:INFO:------------------------------------------------------------------------------------------------
2020-04-25 12:57:40,047:INFO:------------------------------------------------------------------------------------------------
2020-04-25 12:58:54,981:INFO:------------------------------------------------------------------------------------------------
2020-04-25 13:00:19,803:INFO:------------------------------------------------------------------------------------------------
2020-04-25 13:00:36,565:INFO:------------------------------------------------------------------------------------------------
2020-04-25 13:02:13,356:INFO:------------------------------------------------------------------------------------------------
2020-04-25 13:02:36,043:INFO:------------------------------------------------------------------------------------------------
2020-04-25 13:05:26,053:INFO:------------------------------------------------------------------------------------------------
2020-04-25 13:05:47,845:INFO:------------------------------------------------------------------------------------------------
2020-04-25 13:08:22,782:INFO:------------------------------------------------------------------------------------------------
2020-04-25 13:08:50,790:INFO:------------------------------------------------------------------------------------------------
2020-04-25 13:09:25,353:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 13:09:25,354:INFO:2
2020-04-25 13:10:54,606:INFO:------------------------------------------------------------------------------------------------
2020-04-25 13:10:55,722:INFO:------------------------------------------------------------------------------------------------
2020-04-25 13:11:07,422:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 13:11:07,422:INFO:3
2020-04-25 13:11:54,323:INFO:ДУГААРЫН ҮНЭ
2020-04-25 13:11:54,326:INFO:20000
2020-04-25 13:12:10,509:INFO:ДУГААРЫН ҮНЭ
2020-04-25 13:12:10,511:INFO:20000
2020-04-25 13:12:47,287:INFO:ДУГААРЫН ZAHIALGA
2020-04-25 13:13:59,806:INFO:------------------------------------------------------------------------------------------------
2020-04-25 13:14:47,462:INFO:------------------------------------------------------------------------------------------------
2020-04-25 13:17:43,552:INFO:------------------------------------------------------------------------------------------------
2020-04-25 13:28:31,961:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 13:28:31,961:INFO:7
2020-04-25 13:28:47,428:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 13:28:47,429:INFO:7
2020-04-25 13:29:04,822:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 13:29:04,822:INFO:7
2020-04-25 13:30:30,328:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 13:30:30,328:INFO:7
2020-04-25 13:30:38,036:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 13:30:38,036:INFO:7
2020-04-25 13:30:40,557:INFO:------------------------------------------------------------------------------------------------
2020-04-25 13:31:24,890:INFO:ДУГААРЫН ҮНЭ
2020-04-25 13:31:24,893:INFO:10000
2020-04-25 13:32:13,334:INFO:ДУГААРЫН ZAHIALGA
2020-04-25 13:32:28,632:INFO:------------------------------------------------------------------------------------------------
2020-04-25 13:32:30,439:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 13:32:30,440:INFO:7
2020-04-25 13:32:44,554:INFO:------------------------------------------------------------------------------------------------
2020-04-25 13:32:45,840:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 13:32:45,840:INFO:7
2020-04-25 13:33:02,627:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 13:33:02,627:INFO:2
2020-04-25 13:34:21,682:INFO:------------------------------------------------------------------------------------------------
2020-04-25 13:34:29,355:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 13:34:29,355:INFO:2
2020-04-25 13:35:33,010:INFO:------------------------------------------------------------------------------------------------
2020-04-25 13:35:35,235:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 13:35:35,235:INFO:2
2020-04-25 13:35:36,727:INFO:------------------------------------------------------------------------------------------------
2020-04-25 13:35:37,557:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 13:35:37,557:INFO:7
2020-04-25 13:36:17,513:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 13:36:17,513:INFO:2
2020-04-25 13:36:22,750:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 13:36:22,750:INFO:2
2020-04-25 13:38:07,330:INFO:ДУГААРЫН ҮНЭ
2020-04-25 13:38:07,332:INFO:10000
2020-04-25 13:38:22,585:INFO:ДУГААРЫН ZAHIALGA
2020-04-25 13:38:27,525:INFO:------------------------------------------------------------------------------------------------
2020-04-25 13:41:45,119:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 13:41:45,119:INFO:7
2020-04-25 13:41:45,550:WARNING:Not Found: /favicon.ico
2020-04-25 13:48:40,080:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 13:48:40,081:INFO:2
2020-04-25 13:49:54,162:INFO:------------------------------------------------------------------------------------------------
2020-04-25 13:53:06,752:INFO:------------------------------------------------------------------------------------------------
2020-04-25 13:57:39,854:INFO:------------------------------------------------------------------------------------------------
2020-04-25 13:57:40,134:INFO:------------------------------------------------------------------------------------------------
2020-04-25 13:58:38,432:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 13:58:38,432:INFO:2
2020-04-25 13:59:44,051:INFO:ДУГААРЫН ҮНЭ
2020-04-25 13:59:44,053:INFO:10000
2020-04-25 14:00:09,944:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:00:11,815:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:00:11,815:INFO:2
2020-04-25 14:00:22,556:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:00:41,133:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:01:05,110:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:01:26,145:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:01:26,145:INFO:7
2020-04-25 14:01:40,851:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:01:40,851:INFO:2
2020-04-25 14:02:18,176:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:02:36,496:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:04:40,698:INFO:ДУГААРЫН ҮНЭ
2020-04-25 14:04:40,700:INFO:5000
2020-04-25 14:04:54,870:INFO:ДУГААРЫН ҮНЭ
2020-04-25 14:04:54,873:INFO:10000
2020-04-25 14:05:04,255:INFO:ДУГААРЫН ZAHIALGA
2020-04-25 14:05:13,234:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:05:26,515:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:05:46,827:INFO:ДУГААРЫН ZAHIALGA
2020-04-25 14:05:48,014:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:07:45,408:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:07:45,409:INFO:2
2020-04-25 14:07:47,043:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:08:50,872:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:09:07,280:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:09:07,280:INFO:7
2020-04-25 14:09:07,643:WARNING:Not Found: /favicon.ico
2020-04-25 14:09:26,904:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:09:26,904:INFO:7
2020-04-25 14:09:29,798:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:09:33,021:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:09:33,783:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:09:40,057:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:09:40,911:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:09:42,312:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:09:45,119:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:09:47,376:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:09:47,654:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:09:48,110:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:09:58,097:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:10:00,425:INFO:ДУГААРЫН ҮНЭ
2020-04-25 14:10:00,428:INFO:5000
2020-04-25 14:10:05,247:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:10:06,158:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:10:06,615:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:10:40,493:INFO:ДУГААРЫН ZAHIALGA
2020-04-25 14:10:44,550:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:10:45,840:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:10:49,455:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:10:49,455:INFO:2
2020-04-25 14:10:58,193:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:11:17,265:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:11:17,266:INFO:7
2020-04-25 14:11:19,704:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:11:19,706:INFO:7
2020-04-25 14:11:20,986:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:11:21,713:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:11:21,714:INFO:7
2020-04-25 14:11:23,000:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:11:23,000:INFO:7
2020-04-25 14:11:27,190:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:11:28,753:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:11:30,175:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:11:30,871:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:11:31,291:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:11:31,291:INFO:7
2020-04-25 14:11:35,469:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:11:46,827:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:11:47,902:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:11:48,255:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:11:48,750:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:11:49,174:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:11:50,902:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:11:51,926:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:12:03,884:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:12:03,885:INFO:7
2020-04-25 14:12:09,948:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:12:11,240:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:12:15,049:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:12:15,050:INFO:2
2020-04-25 14:12:25,714:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:12:27,965:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:12:29,274:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:12:29,274:INFO:2
2020-04-25 14:12:30,405:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:12:30,405:INFO:7
2020-04-25 14:12:32,181:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:12:32,181:INFO:7
2020-04-25 14:14:12,934:INFO:ДУГААРЫН ҮНЭ
2020-04-25 14:14:12,937:INFO:5000
2020-04-25 14:14:49,836:INFO:ДУГААРЫН ZAHIALGA
2020-04-25 14:16:50,016:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:17:22,785:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:17:25,014:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:17:25,014:INFO:7
2020-04-25 14:17:28,302:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:17:28,303:INFO:7
2020-04-25 14:17:32,471:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:17:32,471:INFO:2
2020-04-25 14:17:39,526:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:17:40,972:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:17:40,972:INFO:7
2020-04-25 14:17:42,665:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:17:42,665:INFO:7
2020-04-25 14:17:43,712:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:17:45,867:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:17:45,867:INFO:7
2020-04-25 14:17:48,396:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:17:48,397:INFO:7
2020-04-25 14:19:17,949:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:19:17,949:INFO:7
2020-04-25 14:19:29,649:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:19:29,649:INFO:7
2020-04-25 14:22:03,575:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:25:54,684:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:25:54,684:INFO:2
2020-04-25 14:25:54,858:WARNING:Not Found: /favicon.ico
2020-04-25 14:25:57,314:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:26:25,942:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 14:26:36,740:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:26:43,917:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:26:43,917:INFO:2
2020-04-25 14:29:10,457:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:29:10,457:INFO:2
2020-04-25 14:29:11,038:WARNING:Not Found: /favicon.ico
2020-04-25 14:31:36,093:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:31:37,157:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:31:37,158:INFO:2
2020-04-25 14:33:52,755:INFO:ДУГААРЫН ҮНЭ
2020-04-25 14:33:52,758:INFO:5000
2020-04-25 14:34:27,351:INFO:ДУГААРЫН ZAHIALGA
2020-04-25 14:34:39,984:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:37:20,944:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:37:23,648:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:37:23,649:INFO:7
2020-04-25 14:37:26,172:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:37:26,173:INFO:7
2020-04-25 14:39:22,310:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:39:22,310:INFO:7
2020-04-25 14:40:30,360:INFO:ДУГААРЫН ҮНЭ
2020-04-25 14:40:30,362:INFO:10000
2020-04-25 14:40:50,571:INFO:ДУГААРЫН ҮНЭ
2020-04-25 14:40:50,574:INFO:10000
2020-04-25 14:41:30,734:INFO:ДУГААРЫН ҮНЭ
2020-04-25 14:41:30,737:INFO:10000
2020-04-25 14:43:23,778:INFO:ДУГААРЫН ZAHIALGA
2020-04-25 14:45:23,986:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:49:54,534:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:51:34,886:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:52:52,422:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:52:52,423:INFO:2
2020-04-25 14:53:07,003:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:53:07,003:INFO:2
2020-04-25 14:53:07,174:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:56:22,717:INFO:ДУГААРЫН ҮНЭ
2020-04-25 14:56:22,719:INFO:5000
2020-04-25 14:57:39,946:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:57:40,230:INFO:------------------------------------------------------------------------------------------------
2020-04-25 14:58:10,035:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:58:10,035:INFO:7
2020-04-25 14:58:16,507:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 14:58:16,507:INFO:2
2020-04-25 14:59:47,022:INFO:ДУГААРЫН ҮНЭ
2020-04-25 14:59:47,025:INFO:5000
2020-04-25 15:00:25,091:INFO:------------------------------------------------------------------------------------------------
2020-04-25 15:00:48,523:INFO:------------------------------------------------------------------------------------------------
2020-04-25 15:02:15,373:INFO:------------------------------------------------------------------------------------------------
2020-04-25 15:02:22,926:INFO:------------------------------------------------------------------------------------------------
2020-04-25 15:02:36,594:INFO:------------------------------------------------------------------------------------------------
2020-04-25 15:05:37,832:INFO:------------------------------------------------------------------------------------------------
2020-04-25 15:05:48,190:INFO:------------------------------------------------------------------------------------------------
2020-04-25 15:06:48,158:INFO:------------------------------------------------------------------------------------------------
2020-04-25 15:06:57,497:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:06:57,497:INFO:7
2020-04-25 15:08:50,978:INFO:------------------------------------------------------------------------------------------------
2020-04-25 15:11:00,546:INFO:------------------------------------------------------------------------------------------------
2020-04-25 15:11:51,040:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:11:51,040:INFO:2
2020-04-25 15:12:06,636:INFO:ДУГААРЫН ҮНЭ
2020-04-25 15:12:06,638:INFO:5000
2020-04-25 15:12:36,983:INFO:ДУГААРЫН ҮНЭ
2020-04-25 15:12:36,986:INFO:5000
2020-04-25 15:13:19,060:INFO:ДУГААРЫН ҮНЭ
2020-04-25 15:13:19,062:INFO:5000
2020-04-25 15:13:23,669:INFO:------------------------------------------------------------------------------------------------
2020-04-25 15:13:24,655:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:13:24,655:INFO:7
2020-04-25 15:17:43,878:INFO:------------------------------------------------------------------------------------------------
2020-04-25 15:23:21,217:INFO:ДУГААРЫН ҮНЭ
2020-04-25 15:23:21,219:INFO:5000
2020-04-25 15:24:00,464:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:24:00,464:INFO:7
2020-04-25 15:24:02,183:INFO:------------------------------------------------------------------------------------------------
2020-04-25 15:24:03,343:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:24:03,344:INFO:7
2020-04-25 15:24:18,400:INFO:------------------------------------------------------------------------------------------------
2020-04-25 15:24:21,338:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:24:21,339:INFO:2
2020-04-25 15:24:21,949:WARNING:Not Found: /favicon.ico
2020-04-25 15:24:22,205:WARNING:Not Found: /favicon.ico
2020-04-25 15:24:29,013:INFO:ДУГААРЫН ZAHIALGA
2020-04-25 15:25:45,795:INFO:------------------------------------------------------------------------------------------------
2020-04-25 15:25:53,139:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:25:53,140:INFO:2
2020-04-25 15:26:29,239:INFO:------------------------------------------------------------------------------------------------
2020-04-25 15:26:50,330:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 212, in getNumber
    if data[1] == az:
IndexError: list index out of range
2020-04-25 15:27:00,487:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:27:00,487:INFO:2
2020-04-25 15:27:33,373:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:27:33,373:INFO:2
2020-04-25 15:27:48,997:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:27:48,997:INFO:2
2020-04-25 15:27:49,012:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:27:49,014:INFO:2
2020-04-25 15:27:49,028:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:27:49,028:INFO:2
2020-04-25 15:27:49,048:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:27:49,048:INFO:2
2020-04-25 15:27:49,060:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:27:49,060:INFO:2
2020-04-25 15:27:49,072:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:27:49,083:INFO:2
2020-04-25 15:27:49,088:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:27:49,092:INFO:2
2020-04-25 15:27:49,111:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:27:49,119:INFO:2
2020-04-25 15:27:49,125:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:27:49,127:INFO:2
2020-04-25 15:27:49,240:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:27:49,240:INFO:2
2020-04-25 15:27:49,264:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:27:49,270:INFO:2
2020-04-25 15:27:49,268:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:27:49,277:INFO:2
2020-04-25 15:27:49,281:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:27:49,298:INFO:2
2020-04-25 15:27:49,393:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:27:49,403:INFO:2
2020-04-25 15:27:49,436:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:27:49,436:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:27:49,437:INFO:2
2020-04-25 15:27:49,437:INFO:2
2020-04-25 15:27:49,439:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:27:49,442:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:27:49,450:INFO:2
2020-04-25 15:27:49,453:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:27:49,454:INFO:2
2020-04-25 15:27:49,463:INFO:2
2020-04-25 15:27:49,571:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:27:49,571:INFO:2
2020-04-25 15:27:49,653:INFO:------------------------------------------------------------------------------------------------
2020-04-25 15:27:54,318:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:27:54,319:INFO:7
2020-04-25 15:27:56,333:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:27:56,333:INFO:7
2020-04-25 15:28:09,220:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:28:09,220:INFO:7
2020-04-25 15:28:12,816:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:28:12,816:INFO:7
2020-04-25 15:28:19,677:INFO:ДУГААРЫН ҮНЭ
2020-04-25 15:28:19,679:INFO:5000
2020-04-25 15:30:03,023:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:30:03,024:INFO:7
2020-04-25 15:30:30,351:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:30:30,351:INFO:7
2020-04-25 15:30:40,341:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:30:40,342:INFO:7
2020-04-25 15:30:56,970:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:30:56,970:INFO:7
2020-04-25 15:31:55,570:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:31:55,570:INFO:2
2020-04-25 15:31:56,032:WARNING:Not Found: /favicon.ico
2020-04-25 15:32:20,898:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 212, in getNumber
    if data[1] == az:
IndexError: list index out of range
2020-04-25 15:33:39,808:INFO:ДУГААРЫН ҮНЭ
2020-04-25 15:33:39,811:INFO:5000
2020-04-25 15:36:55,563:INFO:ДУГААРЫН ҮНЭ
2020-04-25 15:36:55,566:INFO:5000
2020-04-25 15:37:34,383:INFO:ДУГААРЫН ZAHIALGA
2020-04-25 15:37:37,139:INFO:------------------------------------------------------------------------------------------------
2020-04-25 15:41:46,240:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:41:46,240:INFO:2
2020-04-25 15:42:07,087:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 15:42:07,087:INFO:2
2020-04-25 15:43:40,423:INFO:ДУГААРЫН ҮНЭ
2020-04-25 15:43:40,425:INFO:5000
2020-04-25 15:43:57,162:INFO:ДУГААРЫН ZAHIALGA
2020-04-25 15:45:57,366:INFO:------------------------------------------------------------------------------------------------
2020-04-25 15:47:23,653:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 212, in getNumber
    if data[1] == az:
IndexError: list index out of range
2020-04-25 15:49:54,810:INFO:------------------------------------------------------------------------------------------------
2020-04-25 15:53:07,589:INFO:------------------------------------------------------------------------------------------------
2020-04-25 15:57:40,042:INFO:------------------------------------------------------------------------------------------------
2020-04-25 15:57:40,320:INFO:------------------------------------------------------------------------------------------------
2020-04-25 16:00:27,431:INFO:------------------------------------------------------------------------------------------------
2020-04-25 16:02:04,670:INFO:------------------------------------------------------------------------------------------------
2020-04-25 16:02:15,464:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 16:02:15,464:INFO:2
2020-04-25 16:02:15,769:WARNING:Not Found: /favicon.ico
2020-04-25 16:02:15,855:INFO:------------------------------------------------------------------------------------------------
2020-04-25 16:02:18,364:INFO:------------------------------------------------------------------------------------------------
2020-04-25 16:02:19,238:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 16:02:19,239:INFO:7
2020-04-25 16:02:27,721:INFO:------------------------------------------------------------------------------------------------
2020-04-25 16:02:36,695:INFO:------------------------------------------------------------------------------------------------
2020-04-25 16:05:35,466:INFO:ДУГААРЫН ҮНЭ
2020-04-25 16:05:35,468:INFO:10000
2020-04-25 16:05:48,371:INFO:------------------------------------------------------------------------------------------------
2020-04-25 16:07:30,074:INFO:ДУГААРЫН ZAHIALGA
2020-04-25 16:07:39,755:INFO:------------------------------------------------------------------------------------------------
2020-04-25 16:07:40,702:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 16:07:40,702:INFO:7
2020-04-25 16:07:45,620:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 16:07:45,620:INFO:7
2020-04-25 16:08:51,102:INFO:------------------------------------------------------------------------------------------------
2020-04-25 16:09:30,224:INFO:------------------------------------------------------------------------------------------------
2020-04-25 16:16:13,477:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 16:16:13,477:INFO:7
2020-04-25 16:16:13,700:WARNING:Not Found: /favicon.ico
2020-04-25 16:16:43,873:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 16:16:43,873:INFO:7
2020-04-25 16:19:39,672:INFO:------------------------------------------------------------------------------------------------
2020-04-25 16:19:39,690:INFO:------------------------------------------------------------------------------------------------
2020-04-25 16:19:58,449:INFO:ДУГААРЫН ҮНЭ
2020-04-25 16:19:58,452:INFO:10000
2020-04-25 16:20:10,608:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 16:20:10,608:INFO:2
2020-04-25 16:20:13,068:WARNING:Not Found: /favicon.ico
2020-04-25 16:20:16,792:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 16:20:16,792:INFO:2
2020-04-25 16:20:18,964:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 16:20:20,919:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 16:20:21,184:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 16:20:21,408:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 16:20:21,640:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 16:20:21,896:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 16:20:22,161:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 16:20:22,440:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 16:20:22,657:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 16:20:23,895:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 16:20:23,895:INFO:2
2020-04-25 16:20:25,529:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 16:20:25,759:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 16:20:25,953:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-25 16:21:08,413:INFO:------------------------------------------------------------------------------------------------
2020-04-25 16:21:14,664:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 16:21:14,664:INFO:7
2020-04-25 16:21:14,928:WARNING:Not Found: /favicon.ico
2020-04-25 16:21:16,215:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 16:21:16,215:INFO:7
2020-04-25 16:21:29,968:INFO:ДУГААРЫН ҮНЭ
2020-04-25 16:21:29,971:INFO:10000
2020-04-25 16:21:39,532:WARNING:Not Found: /
2020-04-25 16:21:42,699:INFO:ДУГААРЫН ZAHIALGA
2020-04-25 16:23:42,792:INFO:------------------------------------------------------------------------------------------------
2020-04-25 16:23:44,467:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 16:23:44,468:INFO:2
2020-04-25 16:25:47,035:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 16:25:47,036:INFO:7
2020-04-25 16:25:49,041:INFO:------------------------------------------------------------------------------------------------
2020-04-25 16:25:50,162:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 16:25:50,163:INFO:7
2020-04-25 16:26:14,472:INFO:ДУГААРЫН ҮНЭ
2020-04-25 16:26:14,474:INFO:10000
2020-04-25 16:26:26,650:INFO:ДУГААРЫН ZAHIALGA
2020-04-25 16:26:40,649:INFO:ДУГААРЫН ҮНЭ
2020-04-25 16:26:40,652:INFO:5000
2020-04-25 16:26:50,897:INFO:ДУГААРЫН ҮНЭ
2020-04-25 16:26:50,899:INFO:5000
2020-04-25 16:26:54,755:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 16:26:54,756:INFO:7
2020-04-25 16:26:58,045:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 16:26:58,045:INFO:2
2020-04-25 16:27:33,031:INFO:------------------------------------------------------------------------------------------------
2020-04-25 16:27:34,496:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 16:27:34,496:INFO:7
2020-04-25 16:27:36,049:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 16:27:36,049:INFO:2
2020-04-25 16:28:26,745:INFO:------------------------------------------------------------------------------------------------
2020-04-25 16:37:36,215:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 16:37:36,215:INFO:7
2020-04-25 16:42:00,767:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 16:42:00,767:INFO:7
2020-04-25 16:45:57,588:INFO:------------------------------------------------------------------------------------------------
2020-04-25 16:46:15,689:INFO:ДУГААРЫН ҮНЭ
2020-04-25 16:46:15,692:INFO:10000
2020-04-25 16:46:35,299:INFO:ДУГААРЫН ZAHIALGA
2020-04-25 16:48:35,539:INFO:------------------------------------------------------------------------------------------------
2020-04-25 16:53:07,906:INFO:------------------------------------------------------------------------------------------------
2020-04-25 16:57:40,173:INFO:------------------------------------------------------------------------------------------------
2020-04-25 16:57:40,456:INFO:------------------------------------------------------------------------------------------------
2020-04-25 17:00:29,736:INFO:------------------------------------------------------------------------------------------------
2020-04-25 17:02:32,707:INFO:------------------------------------------------------------------------------------------------
2020-04-25 17:08:51,218:INFO:------------------------------------------------------------------------------------------------
2020-04-25 17:09:47,600:INFO:------------------------------------------------------------------------------------------------
2020-04-25 17:10:03,470:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 17:10:03,470:INFO:2
2020-04-25 17:10:04,869:INFO:------------------------------------------------------------------------------------------------
2020-04-25 17:10:05,707:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 17:10:05,707:INFO:7
2020-04-25 17:11:12,619:INFO:------------------------------------------------------------------------------------------------
2020-04-25 17:11:58,405:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 17:11:58,405:INFO:2
2020-04-25 17:12:22,166:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 17:12:22,166:INFO:7
2020-04-25 17:12:24,261:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 17:12:24,261:INFO:7
2020-04-25 17:13:15,324:INFO:ДУГААРЫН ҮНЭ
2020-04-25 17:13:15,326:INFO:5000
2020-04-25 17:16:19,887:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 17:16:19,888:INFO:7
2020-04-25 17:17:28,654:INFO:------------------------------------------------------------------------------------------------
2020-04-25 17:17:32,798:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 17:17:32,798:INFO:2
2020-04-25 17:21:24,052:INFO:------------------------------------------------------------------------------------------------
2020-04-25 17:21:32,524:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 17:21:32,524:INFO:2
2020-04-25 17:21:32,956:WARNING:Not Found: /favicon.ico
2020-04-25 17:32:30,586:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 17:32:30,586:INFO:2
2020-04-25 17:36:33,232:INFO:------------------------------------------------------------------------------------------------
2020-04-25 17:38:31,814:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 17:38:31,814:INFO:2
2020-04-25 17:38:32,674:WARNING:Not Found: /favicon.ico
2020-04-25 17:39:35,829:INFO:ДУГААРЫН ҮНЭ
2020-04-25 17:39:35,832:INFO:5000
2020-04-25 17:48:35,796:INFO:------------------------------------------------------------------------------------------------
2020-04-25 17:53:08,224:INFO:------------------------------------------------------------------------------------------------
2020-04-25 17:56:41,237:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 17:56:41,237:INFO:2
2020-04-25 17:56:43,710:INFO:------------------------------------------------------------------------------------------------
2020-04-25 17:56:45,163:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 17:56:45,164:INFO:7
2020-04-25 17:57:40,269:INFO:------------------------------------------------------------------------------------------------
2020-04-25 17:57:40,568:INFO:------------------------------------------------------------------------------------------------
2020-04-25 18:02:37,415:INFO:------------------------------------------------------------------------------------------------
2020-04-25 18:09:42,968:INFO:------------------------------------------------------------------------------------------------
2020-04-25 18:09:44,776:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 18:09:44,776:INFO:7
2020-04-25 18:09:59,164:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 18:09:59,165:INFO:7
2020-04-25 18:10:01,461:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 18:10:01,461:INFO:7
2020-04-25 18:10:03,067:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 18:10:03,067:INFO:7
2020-04-25 18:10:26,468:INFO:------------------------------------------------------------------------------------------------
2020-04-25 18:10:28,929:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 18:10:28,929:INFO:7
2020-04-25 18:10:30,061:INFO:------------------------------------------------------------------------------------------------
2020-04-25 18:10:31,237:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 18:10:31,237:INFO:7
2020-04-25 18:10:46,344:INFO:ДУГААРЫН ҮНЭ
2020-04-25 18:10:46,347:INFO:10000
2020-04-25 18:10:51,469:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 18:10:51,469:INFO:7
2020-04-25 18:10:57,952:INFO:------------------------------------------------------------------------------------------------
2020-04-25 18:10:59,543:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 18:10:59,544:INFO:7
2020-04-25 18:11:01,257:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 18:11:01,257:INFO:7
2020-04-25 18:12:39,911:INFO:------------------------------------------------------------------------------------------------
2020-04-25 18:12:47,215:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 18:12:47,215:INFO:7
2020-04-25 18:18:30,485:INFO:------------------------------------------------------------------------------------------------
2020-04-25 18:18:31,757:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 18:18:31,757:INFO:2
2020-04-25 18:18:32,680:INFO:------------------------------------------------------------------------------------------------
2020-04-25 18:18:33,451:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 18:18:33,451:INFO:7
2020-04-25 18:27:37,350:INFO:------------------------------------------------------------------------------------------------
2020-04-25 18:27:38,580:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 18:27:38,580:INFO:2
2020-04-25 18:27:40,022:INFO:------------------------------------------------------------------------------------------------
2020-04-25 18:27:40,723:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-25 18:27:40,724:INFO:7
2020-04-25 18:28:18,932:INFO:ДУГААРЫН ҮНЭ
2020-04-25 18:28:18,934:INFO:10000
2020-04-25 18:28:33,895:INFO:ДУГААРЫН ZAHIALGA
2020-04-25 18:30:34,021:INFO:------------------------------------------------------------------------------------------------
2020-04-25 18:53:08,929:INFO:------------------------------------------------------------------------------------------------
2020-04-25 18:57:40,379:INFO:------------------------------------------------------------------------------------------------
2020-04-25 18:57:40,677:INFO:------------------------------------------------------------------------------------------------
2020-04-25 19:02:42,140:INFO:------------------------------------------------------------------------------------------------
2020-04-25 19:30:34,134:INFO:------------------------------------------------------------------------------------------------
2020-04-25 19:42:58,161:INFO:------------------------------------------------------------------------------------------------
2020-04-25 19:53:09,251:INFO:------------------------------------------------------------------------------------------------
2020-04-25 19:57:40,472:INFO:------------------------------------------------------------------------------------------------
2020-04-25 19:57:40,767:INFO:------------------------------------------------------------------------------------------------
2020-04-25 20:02:46,865:INFO:------------------------------------------------------------------------------------------------
2020-04-25 20:30:38,703:INFO:------------------------------------------------------------------------------------------------
2020-04-25 20:42:58,393:INFO:------------------------------------------------------------------------------------------------
2020-04-25 20:53:09,594:INFO:------------------------------------------------------------------------------------------------
2020-04-25 21:02:51,640:INFO:------------------------------------------------------------------------------------------------
2020-04-25 21:42:58,614:INFO:------------------------------------------------------------------------------------------------
2020-04-25 21:53:09,916:INFO:------------------------------------------------------------------------------------------------
2020-04-25 22:02:56,343:INFO:------------------------------------------------------------------------------------------------
2020-04-25 22:22:31,853:WARNING:Not Found: /robots.txt
2020-04-25 22:53:10,297:INFO:------------------------------------------------------------------------------------------------
2020-04-25 23:03:01,076:INFO:------------------------------------------------------------------------------------------------
2020-04-25 23:53:10,698:INFO:------------------------------------------------------------------------------------------------
2020-04-26 00:03:05,844:INFO:------------------------------------------------------------------------------------------------
2020-04-26 00:53:11,125:INFO:------------------------------------------------------------------------------------------------
2020-04-26 01:03:10,663:INFO:------------------------------------------------------------------------------------------------
2020-04-26 01:30:57,562:INFO:------------------------------------------------------------------------------------------------
2020-04-26 01:53:11,691:INFO:------------------------------------------------------------------------------------------------
2020-04-26 02:03:15,696:INFO:------------------------------------------------------------------------------------------------
2020-04-26 02:18:19,108:WARNING:Not Found: /
2020-04-26 02:30:59,767:INFO:------------------------------------------------------------------------------------------------
2020-04-26 02:34:55,316:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 02:34:55,316:INFO:7
2020-04-26 02:34:55,734:WARNING:Not Found: /favicon.ico
2020-04-26 02:53:12,135:INFO:------------------------------------------------------------------------------------------------
2020-04-26 03:03:20,694:INFO:------------------------------------------------------------------------------------------------
2020-04-26 03:31:01,925:INFO:------------------------------------------------------------------------------------------------
2020-04-26 03:53:12,772:INFO:------------------------------------------------------------------------------------------------
2020-04-26 04:03:25,426:INFO:------------------------------------------------------------------------------------------------
2020-04-26 04:31:04,136:INFO:------------------------------------------------------------------------------------------------
2020-04-26 04:51:54,535:WARNING:Not Found: /
2020-04-26 04:53:13,046:INFO:------------------------------------------------------------------------------------------------
2020-04-26 05:03:30,419:INFO:------------------------------------------------------------------------------------------------
2020-04-26 05:31:06,292:INFO:------------------------------------------------------------------------------------------------
2020-04-26 05:53:13,394:INFO:------------------------------------------------------------------------------------------------
2020-04-26 06:03:35,227:INFO:------------------------------------------------------------------------------------------------
